{{- if .Values.rbac.create -}}
# ServiceAccount for the static operator controller
# Manages Static CRD lifecycle and creates Deployments/Services
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
# ServiceAccount for static service pods
# Allows pods to watch StaticAPI CRDs directly from Kubernetes API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.static.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: static-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
# Role for static-service to read StaticAPI resources in its namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: static-service-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: static-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - static.io
  resources:
  - staticapis
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: static-service-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: static-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: static-service-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.static.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
# ClusterRole for the operator to manage all Static resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operator.name }}-role
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - static.io
  resources:
  - staticapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - static.io
  resources:
  - staticapis/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - static.io
  resources:
  - statics
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - static.io
  resources:
  - statics/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.operator.name }}-rolebinding
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.operator.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
